#include <gtest/gtest.h>
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>

#include "system/jit_ir.h"
#include "system/memory_bus.h"
#include "data/arena_alloc.h"
#include "data/ir_node.h"
#include "util/ir_printer.h"

TEST(IrGen, FuzzerManualDump) {
    // 1. Open the file generated by fuzzer.py
    std::ifstream infile("analysis/fuzzer_out/fuzzer.txt");
    ASSERT_TRUE(infile.is_open()) << "Could not open fuzzer.txt. Did you run scripts/fuzzer.py?";

    // 2. Open the output dump file
    std::ofstream outfile("analysis/fuzzer_out/ir_manual_dump.txt");
    ASSERT_TRUE(outfile.is_open()) << "Could not open output dump file.";

    std::string line;
    int count = 1;

    // 3. Process each instruction
    while (std::getline(infile, line)) {
        if (line.empty()) continue;

        // Parse the tab-separated line (Hex \t Asm \t ExpectedOp)
        std::istringstream iss(line);
        std::string hex_str, asm_str, expected_op;
        std::getline(iss, hex_str, '\t');
        std::getline(iss, asm_str, '\t');
        std::getline(iss, expected_op, '\t');

        if (hex_str.empty() || asm_str.empty()) continue;

        // Convert "0xe0800001" to an integer
        uint32_t instr = std::stoul(hex_str, nullptr, 16);

        // Setup the builder and memory
        ArenaAllocator arena(4096);
        MemoryBus bus;
        IrBuilder builder(&bus, &arena);

        bus.Write32(0x08000000, instr);
        bus.Write32(0x08000004, 0xEAFFFFFE);  // B . sentinel so block ends

        // Generate IR
        builder.BuildBlock<false>(0x08000000);

        // Write to the dump file
        outfile << "========== Instruction " << count++ << " ==========\n";
        outfile << "Encoding: " << hex_str << "\n";
        outfile << "Assembly: " << asm_str << "\n";
        outfile << "--- IR (micro-ops) ---\n";
        outfile << IrPrinter::PrintArena(&arena, 0x08000000);
        outfile << "================================\n\n";
    }

    std::cout << "Successfully dumped " << (count - 1) 
              << " instructions to analysis/fuzzer_out/ir_manual_dump.txt\n";
}